import {
  CheckCircle2,
  Clock,
  XCircle,
  AlertCircle,
  MapPin,
  CalendarDays,
  BedDouble,
  UserCheck,
  Scissors,
  DollarSign,
  Shield,
  Star,
  BarChart2,
  TrendingUp,
  Calendar,
  Users,
  Stethoscope,
  Receipt,
  MessageSquare,
  Camera,
  Layers,
  Phone,
  Award,
} from "lucide-react";

export const NAV = [
  { id: "overview", label: "Overview", icon: BarChart2 },
  { id: "analytics", label: "Analytics", icon: TrendingUp },
  { id: "bookings", label: "Bookings", icon: Calendar },
  { id: "patients", label: "Patients", icon: Users },
  { id: "doctors", label: "Doctors", icon: Stethoscope },
  { id: "billing", label: "Billing", icon: Receipt },
  { id: "reviews", label: "Reviews", icon: MessageSquare },
  { id: "gallery", label: "Gallery", icon: Camera },
  { id: "departments", label: "Departments", icon: Layers },
  { id: "contact", label: "Contact", icon: Phone },
  { id: "hours", label: "Hours", icon: Clock },
  { id: "awards", label: "Awards", icon: Award },
  { id: "services", label: "Manage Services", icon: Layers },
];


export const FACILITY = {
  name: "Meridian General Hospital",
  type: "Multi-Specialty",
  facilityType: "hospital",
  accreditation: "JCI Accredited",
  location: "42 Wellness Blvd, Manhattan, New York, NY 10001",
  phone: "+1 (212) 555-0192",
  emergency: "+1 (212) 555-9911",
  email: "info@meridianhospital.com",
  website: "www.meridianhospital.com",
  rating: 4.8,
  reviewsCount: 1240,
  established: "1987",
  beds: "620",
  doctors: "185",
  surgeries: "8,400+",
  priceRange: "$$$ — Premium",
  acceptingPatients: true,
  approvedDate: "March 1, 2026",
  about:
    "Meridian General Hospital is a leading multi-specialty medical center committed to delivering world-class healthcare with compassion and precision. Founded in 1987, we've grown into one of New York's most trusted hospitals, combining cutting-edge technology with a deeply patient-centered approach.",
  images: [
    "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&q=80",
    "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
    "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&q=80",
    "https://images.unsplash.com/photo-1629909615184-74f495363b67?w=800&q=80",
    "https://images.unsplash.com/photo-1551884831-bbf3cdc6469e?w=800&q=80",
  ],
  departments: [
    {
      name: "Cardiology",
      head: "Dr. Priya Mehta",
      specialties: "Interventional Cardiology, Echocardiography",
      description:
        "Comprehensive cardiac care with state-of-the-art catheterization labs.",
    },
    {
      name: "Neurology",
      head: "Dr. Samuel Torres",
      specialties: "Stroke Care, Epilepsy, Neurodegenerative Disorders",
      description: "Nationally recognized stroke center.",
    },
    {
      name: "Orthopedics",
      head: "Dr. Kenji Watanabe",
      specialties: "Joint Replacement, Sports Medicine, Spine Surgery",
      description: "Robotic-assisted joint replacements.",
    },
    {
      name: "Oncology",
      head: "Dr. Fatima Al-Rashid",
      specialties: "Medical Oncology, Radiation, Hematology",
      description: "Integrated cancer care with clinical trials.",
    },
    {
      name: "Emergency Medicine",
      head: "Dr. Carlos Rivera",
      specialties: "Trauma, Critical Care, Toxicology",
      description: "Level I Trauma Center, 24/7.",
    },
  ],
  insurances: [
    "Aetna",
    "BlueCross BlueShield",
    "Cigna",
    "Humana",
    "Medicare",
    "Medicaid",
    "UnitedHealthcare",
  ],
  facilities: [
    "ICU",
    "Emergency Room",
    "Operating Theatres",
    "MRI",
    "CT Scan",
    "X-Ray",
    "Blood Bank",
    "Pharmacy",
    "NICU",
    "Dialysis",
    "Cafeteria",
    "Parking",
    "Helipad",
  ],
  services: [
    { name: "MRI Scan", price: "$400–$1,200" },
    { name: "CT Scan", price: "$300–$900" },
    { name: "Cardiac Catheterization", price: "$3,500–$8,000" },
    { name: "Joint Replacement Surgery", price: "$25,000–$45,000" },
    { name: "Chemotherapy Session", price: "$2,000–$12,000" },
    { name: "General Consultation", price: "$150–$350" },
    { name: "Emergency Room Visit", price: "$500–$3,000" },
    { name: "Blood Panel (Full)", price: "$80–$200" },
  ],
  keyDoctors: [
    {
      name: "Dr. Priya Mehta",
      specialty: "Cardiologist",
      experience: "22 yrs",
      availability: "Mon–Fri 9–5",
      patients: 340,
    },
    {
      name: "Dr. Samuel Torres",
      specialty: "Neurologist",
      experience: "18 yrs",
      availability: "Tue–Sat 8–4",
      patients: 290,
    },
    {
      name: "Dr. Kenji Watanabe",
      specialty: "Orthopedic Surgeon",
      experience: "15 yrs",
      availability: "Mon–Thu 10–6",
      patients: 210,
    },
    {
      name: "Dr. Fatima Al-Rashid",
      specialty: "Oncologist",
      experience: "20 yrs",
      availability: "Mon–Fri 9–3",
      patients: 180,
    },
    {
      name: "Dr. Carlos Rivera",
      specialty: "Emergency Physician",
      experience: "12 yrs",
      availability: "24/7 On-Call",
      patients: 420,
    },
    {
      name: "Dr. Anita Sharma",
      specialty: "Pediatrician",
      experience: "10 yrs",
      availability: "Mon–Fri 9–5",
      patients: 260,
    },
  ],
  accreditationsList: ["JCI", "The Joint Commission", "ISO 9001", "ACHC"],
  awards: [
    {
      title: "Best Hospital in New York",
      year: "2024",
      desc: "Awarded by U.S. News & World Report.",
    },
    {
      title: "Top 50 Cardiac Programs",
      year: "2023",
      desc: "Recognized by Healthgrades.",
    },
    {
      title: "Patient Safety Excellence",
      year: "2023",
      desc: "Leapfrog Group A rating.",
    },
  ],
  businessHours: [
    { day: "Monday", time: "08:00–20:00", isOpen: true, highlight: true },
    { day: "Tuesday", time: "08:00–20:00", isOpen: true, highlight: false },
    { day: "Wednesday", time: "08:00–20:00", isOpen: true, highlight: false },
    { day: "Thursday", time: "08:00–20:00", isOpen: true, highlight: false },
    { day: "Friday", time: "08:00–18:00", isOpen: true, highlight: false },
    { day: "Saturday", time: "09:00–14:00", isOpen: true, highlight: true },
    { day: "Sunday", time: "", isOpen: false, highlight: false },
  ],
};

/* ══════════════ ANALYTICS DATA ══════════════ */
export const visitData = [
  { month: "Jan", visits: 420, revenue: 84000, bookings: 138 },
  { month: "Feb", visits: 380, revenue: 72000, bookings: 121 },
  { month: "Mar", visits: 510, revenue: 98000, bookings: 165 },
  { month: "Apr", visits: 470, revenue: 91000, bookings: 150 },
  { month: "May", visits: 620, revenue: 118000, bookings: 200 },
  { month: "Jun", visits: 580, revenue: 112000, bookings: 188 },
  { month: "Jul", visits: 710, revenue: 135000, bookings: 230 },
  { month: "Aug", visits: 690, revenue: 130000, bookings: 222 },
  { month: "Sep", visits: 760, revenue: 148000, bookings: 245 },
  { month: "Oct", visits: 820, revenue: 160000, bookings: 265 },
  { month: "Nov", visits: 780, revenue: 152000, bookings: 252 },
  { month: "Dec", visits: 890, revenue: 175000, bookings: 288 },
];
export const deptData = [
  { name: "Cardiology", patients: 340 },
  { name: "Neurology", patients: 290 },
  { name: "Orthopedics", patients: 210 },
  { name: "Oncology", patients: 180 },
  { name: "Emergency", patients: 420 },
  { name: "Pediatrics", patients: 260 },
];
export const statusData = [
  { name: "Accepted", value: 142, color: "#10b981" },
  { name: "Pending", value: 68, color: "#f59e0b" },
  { name: "Cancelled", value: 34, color: "#ef4444" },
];


export const initBookings = [
  {
    id: "BK001",
    patient: "Aiden Clark",
    doctor: "Dr. Priya Mehta",
    dept: "Cardiology",
    date: "2026-03-06",
    time: "10:00 AM",
    status: "accepted",
    amount: "$350",
    type: "Consultation",
  },
  {
    id: "BK002",
    patient: "Sophia Nguyen",
    doctor: "Dr. Samuel Torres",
    dept: "Neurology",
    date: "2026-03-06",
    time: "11:30 AM",
    status: "pending",
    amount: "$280",
    type: "Follow-up",
  },
  {
    id: "BK003",
    patient: "Marcus Johnson",
    doctor: "Dr. Kenji Watanabe",
    dept: "Orthopedics",
    date: "2026-03-07",
    time: "09:00 AM",
    status: "accepted",
    amount: "$420",
    type: "Consultation",
  },
  {
    id: "BK004",
    patient: "Lena Torres",
    doctor: "Dr. Fatima Al-Rashid",
    dept: "Oncology",
    date: "2026-03-07",
    time: "02:00 PM",
    status: "cancelled",
    amount: "$500",
    type: "Consultation",
  },
  {
    id: "BK005",
    patient: "James Kim",
    doctor: "Dr. Carlos Rivera",
    dept: "Emergency",
    date: "2026-03-08",
    time: "08:00 AM",
    status: "accepted",
    amount: "$800",
    type: "Emergency",
  },
  {
    id: "BK006",
    patient: "Priya Desai",
    doctor: "Dr. Anita Sharma",
    dept: "Pediatrics",
    date: "2026-03-08",
    time: "03:00 PM",
    status: "pending",
    amount: "$200",
    type: "Checkup",
  },
  {
    id: "BK007",
    patient: "Robert Chen",
    doctor: "Dr. Priya Mehta",
    dept: "Cardiology",
    date: "2026-03-09",
    time: "10:30 AM",
    status: "accepted",
    amount: "$350",
    type: "Follow-up",
  },
  {
    id: "BK008",
    patient: "Amara Osei",
    doctor: "Dr. Samuel Torres",
    dept: "Neurology",
    date: "2026-03-09",
    time: "01:00 PM",
    status: "pending",
    amount: "$280",
    type: "Consultation",
  },
  {
    id: "BK009",
    patient: "David Walsh",
    doctor: "Dr. Kenji Watanabe",
    dept: "Orthopedics",
    date: "2026-03-10",
    time: "11:00 AM",
    status: "accepted",
    amount: "$420",
    type: "Surgery Prep",
  },
  {
    id: "BK010",
    patient: "Nadia Al-Farsi",
    doctor: "Dr. Carlos Rivera",
    dept: "Emergency",
    date: "2026-03-10",
    time: "05:30 PM",
    status: "cancelled",
    amount: "$600",
    type: "Emergency",
  },
];


export const initBills = [
  {
    id: "INV-2026-001",
    patient: "Aiden Clark",
    date: "2026-03-06",
    amount: "$350",
    status: "paid",
    items: [{ desc: "Cardiology Consultation", qty: 1, rate: 350 }],
    doctor: "Dr. Priya Mehta",
    prescription: "Aspirin 81mg daily, Atorvastatin 40mg nightly",
  },
  {
    id: "INV-2026-002",
    patient: "Marcus Johnson",
    date: "2026-03-07",
    amount: "$1,420",
    status: "paid",
    items: [
      { desc: "Orthopedic Consultation", qty: 1, rate: 420 },
      { desc: "X-Ray (2 views)", qty: 2, rate: 200 },
      { desc: "MRI Knee", qty: 1, rate: 600 },
    ],
    doctor: "Dr. Kenji Watanabe",
    prescription: "Ibuprofen 600mg TDS, Physiotherapy 3x/week",
  },
  {
    id: "INV-2026-003",
    patient: "James Kim",
    date: "2026-03-08",
    amount: "$800",
    status: "pending",
    items: [
      { desc: "Emergency Room Visit", qty: 1, rate: 500 },
      { desc: "Blood Panel", qty: 1, rate: 180 },
      { desc: "IV Fluids", qty: 1, rate: 120 },
    ],
    doctor: "Dr. Carlos Rivera",
    prescription: "Amoxicillin 500mg TDS x7 days, Rest",
  },
  {
    id: "INV-2026-004",
    patient: "Robert Chen",
    date: "2026-03-09",
    amount: "$350",
    status: "paid",
    items: [{ desc: "Cardiology Follow-up", qty: 1, rate: 350 }],
    doctor: "Dr. Priya Mehta",
    prescription: "Continue current medications, Repeat Echo in 3 months",
  },
  {
    id: "INV-2026-005",
    patient: "David Walsh",
    date: "2026-03-10",
    amount: "$2,200",
    status: "pending",
    items: [
      { desc: "Orthopedic Surgery Prep", qty: 1, rate: 420 },
      { desc: "Pre-op Blood Work", qty: 1, rate: 280 },
      { desc: "Anesthesia Consult", qty: 1, rate: 300 },
      { desc: "CT Scan Hip", qty: 1, rate: 1200 },
    ],
    doctor: "Dr. Kenji Watanabe",
    prescription: "NPO after midnight, Bisoprolol 5mg morning of surgery",
  },
];


export const initReviews = [
  {
    id: 1,
    name: "Sarah Mitchell",
    rating: 5,
    date: "Feb 28, 2026",
    text: "Exceptional care from Dr. Mehta. The cardiology team was professional and thorough. I felt completely at ease throughout my entire stay.",
    dept: "Cardiology",
    avatar: "SM",
    reply: "",
  },
  {
    id: 2,
    name: "James Okonkwo",
    rating: 4,
    date: "Feb 25, 2026",
    text: "Good experience overall. The emergency department was quick and efficient. Minor wait time at check-in but the actual care was excellent.",
    dept: "Emergency",
    avatar: "JO",
    reply:
      "Thank you for your feedback, James! We are continuously working to improve our check-in process.",
  },
  {
    id: 3,
    name: "Priya Nair",
    rating: 5,
    date: "Feb 20, 2026",
    text: "Dr. Al-Rashid is an outstanding oncologist. Her compassionate approach during a very difficult time made all the difference for our family.",
    dept: "Oncology",
    avatar: "PN",
    reply: "",
  },
  {
    id: 4,
    name: "David Steinberg",
    rating: 3,
    date: "Feb 18, 2026",
    text: "The medical care was good but the administrative process was confusing. Billing took longer than expected to resolve. Hope this improves.",
    dept: "Orthopedics",
    avatar: "DS",
    reply: "",
  },
  {
    id: 5,
    name: "Aiko Tanaka",
    rating: 5,
    date: "Feb 15, 2026",
    text: "Best hospital experience I've had. Clean facilities, attentive nursing staff, and Dr. Torres took the time to explain everything in detail.",
    dept: "Neurology",
    avatar: "AT",
    reply:
      "We're thrilled to hear this, Aiko! Dr. Torres and the team appreciate your kind words.",
  },
  {
    id: 6,
    name: "Carlos Mendez",
    rating: 4,
    date: "Feb 10, 2026",
    text: "Pediatrics department was wonderful with my daughter. Dr. Sharma was gentle and patient. Would definitely recommend to other parents.",
    dept: "Pediatrics",
    avatar: "CM",
    reply: "",
  },
];

export const GRADS = [
  "from-green-500 to-violet-600",
  "from-teal-500 to-emerald-500",
  "from-green-500 to-lime-400",
  "from-teal-500 to-cyan-500",
  "from-rose-500 to-pink-500",
  "from-fuchsia-500 to-purple-500",
];

export const statusBg = {
  accepted:
    "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-500/10 dark:text-emerald-400 dark:border-emerald-500/20",
  pending:
    "bg-green-50 text-green-700 border-green-200 dark:bg-green-500/10 dark:text-green-400 dark:border-green-500/20",
  cancelled:
    "bg-rose-50 text-rose-600 border-rose-200 dark:bg-rose-500/10 dark:text-rose-400 dark:border-rose-500/20",
  paid: "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-500/10 dark:text-emerald-400 dark:border-emerald-500/20",
  unpaid:
    "bg-rose-50 text-rose-600 border-rose-200 dark:bg-rose-500/10 dark:text-rose-400 dark:border-rose-500/20",
};
export const initials = (n) =>
  n
    .split(" ")
    .map((w) => w[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
export const fmt = (n) =>
  typeof n === "number"
    ? n >= 1000
      ? `$${(n / 1000).toFixed(0)}k`
      : `$${n}`
    : n;
